task: classification # classification/survival
task_settings:
  outcomes: [ "os_months_6", "os_months_24", "DCR", "ORR" ]
  loss: mm_loss # mm_survival_loss  mm_loss

training_type: cross_validation # hyperparameter_tuning  # cross_validation_stratified
data-type: hypothesis_driven  # hypothesis_driven/data_driven
source: pyrad  # pyrad/foundation
imp: noimp  # noimp/imp
seed: [0]

use_early_stopping: true
prepare_dataset: false

train_df: [ "data/features_dataset_radpy.parquet", "data/features_dataset_radfm.parquet" ]
annotation_file: data/annotations_INT.csv

mods:
  - rwd: true # rwd: true
    radpy: false
    dp: false
    genomics: false
  - rwd: true # rwd: true
    radpy: false
    dp: true
    genomics: false
  - rwd: true # rwd: true
    radpy: true
    dp: false
    genomics: false
  - rwd: true # rwd: true
    radpy: true
    dp: true
    genomics: false
  - rwd: true # rwd: true
    radpy: true
    dp: true
    genomics: true
  - rwd: true # rwd: true
    radfm: true
    dp: false
    genomics: false
  - rwd: true # rwd: true
    radfm: true
    dp: true
    genomics: false
  - rwd: true # rwd: true
    radfm: true
    dp: true
    genomics: true

  
folds:
  cross_validation_stratified:
    - GHD_2
    - INT_2
    - MH_2
    - SZMC_2
    - VHIO_2
    - GHD_3
    - INT_3
    - MH_3
    - SZMC_3
    - VHIO_3
  cross_validation:
    - INT_sub1
    - INT_sub2
    - INT_sub3
    - INT_sub4
    - INT_sub5
  standard:
    - ALL

# grid search
hyperparameters:
  batch_size: [16, 32, 64, 128]  # list needed also for single value
  reconstruction_weight: [0.01, 0.03, 0.1, 0.3]
  n_layers: [1, 2]

# default hyperparameters
hyperparameters_default:
  batch_size: 64
  reconstruction_weight: 0.1
  n_layers: 1

# --- CONFIG FLAGS ---
#  USE_COHORT2_FILTER: [ true ]
#  FILTER_SQUAMOUS: ["0.0", "1.0"]  # NSCLC_HISTOLOGY_SQUAMOUS == 1
#  FILTER_CHEMO_IMMUNO: ["0", "1"]
FILTER_INT: [ true ]  # filter INT cohort

